Repository taing-project-team/taing, pull requests merged in 2023-10, with the labels that each got.

#98 Refactor/auth state
  src/hooks/auth/useAuthState.ts
  src/hooks/useRedirect.ts
  src/pages/FindId/FindId.tsx
  src/pages/FindPassword/FindPassword.tsx
  src/pages/Home/Home.tsx
  src/pages/LogIn/LogIn.tsx
  src/pages/LoginSelection/LoginSelection.tsx
  src/pages/OnBoarding/OnBoarding.tsx
  src/pages/SignUp/SignUp.tsx
Labels: ✨feature

#97 Feature/search
  src/components/Header/Header.tsx
  src/components/SearchModal/SearchModal.module.scss
  src/components/SearchModal/SearchModal.tsx
Labels: ✨feature

#102 Refactor/auth state redirect
  src/components/LogoutModal/LogoutModal.tsx
  src/hooks/auth/useSignOut.ts
  src/pages/Home/Home.tsx
Labels: 🐛bug

#103 Refector/search
  src/components/SearchModal/SearchModal.module.scss
  src/components/SearchModal/SearchModal.tsx
Labels: ♻️refactor

#105 Feature/profile
  src/components/Header/Header.module.scss
  src/components/Header/Header.tsx
  src/components/ProfileList/ProfileList.module.scss
  src/components/ProfileList/ProfileList.tsx
  src/components/ProfileModal/ProfileModal.module.scss
  src/components/ProfileModal/ProfileModal.tsx
  src/constants/constants.ts
  src/hooks/firestore/useCreateAuthUser.ts
  src/hooks/firestore/useUpdateData.ts
  src/hooks/useReadData.ts
  src/pages/Profile/Profile.tsx
  src/pages/ProfileEdit/ProfileEdit.tsx
  src/state/profileState.ts
  src/type.ts
Labels: ✨feature

#112 Refactor/profile
  src/components/Header/Header.tsx
  src/pages/Profile/Profile.tsx
  src/pages/ProfileEdit/ProfileEdit.module.scss
  src/pages/ProfileEdit/ProfileEdit.tsx
  src/routes/router.tsx
Labels: ♻️refactor

#113 Refactor/detail/chaewon
  src/components/SwiperContent/SwiperContent.tsx
  src/hooks/useReadData.ts
  src/type.ts
Labels: ♻️refactor

#114 Refector/detail/esther
  src/components/Footer/Footer.module.scss
  src/components/Header/Header.module.scss
  src/components/PopupModal/PopupModal.tsx
  src/components/common/DummyLink/DummyLink.tsx
  src/hooks/auth/useSignUp.ts
  src/pages/Home/Home.tsx
  src/pages/SignUp/SignUp.tsx
  src/utils/hasDayPassed.ts
Labels: ♻️refactor

#116 ♻️ favicon 및 title 변경 #115
  index.html
  public/logo.svg
Labels: ♻️refactor

#123 Refector/performance/esther
  src/App.tsx
  src/assets/images/main_banner.png
  src/assets/images/popup_image.png
  src/assets/images/popup_image.webp
  src/assets/images/sports_banner.png
  src/components/MainBanner/MainBanner.module.scss
  src/components/MainBanner/MainBanner.tsx
  src/components/PopupModal/PopupModal.tsx
  src/components/SearchModal/SearchModal.tsx
  src/components/SwiperContent/SwiperContent.tsx
  src/pages/ErrorPage/ErrorPage.tsx
  src/pages/Home/Home.module.scss
  src/pages/Home/Home.tsx
  src/pages/LogIn/LogIn.tsx
  src/pages/SignUp/SignUp.tsx
Labels: ♻️refactor
