Repository taing-project-team/taing, pull requests merged in 2023-09, with the labels that each got.

#3 💄 : "공통 버튼 컴포넌트 UI 생성"
  src/components/common/Button.tsx
  src/components/common/Button/Button.module.scss
  src/components/common/Button/Button.tsx
Labels: ✨feature

#6 ⚡️ : "type에 따른 공통 버튼 분리 " #1
  src/components/common/Button/Button.module.scss
  src/components/common/Button/Button.tsx
Labels: ♻️refactor

#10 Style/footer
  src/App.tsx
  src/assets/styles/variables.scss
  src/components/Footer/Footer.module.scss
  src/components/Footer/Footer.tsx
Labels: ✨feature

#9 💄 : "header UI 완성 및 스크롤애니메이션 적용"
  package-lock.json
  package.json
  src/App.tsx
  src/components/header/Header.module.scss
  src/components/header/Header.tsx
Labels: ✨feature

#13 input과 footer의 style 코드 수정
  src/App.tsx
  src/components/Footer/Footer.module.scss
  src/components/common/Input/Input.module.scss
Labels: ♻️refactor

#22 [style] 로그인, 회원가입 관련 페이지 UI 구현
  src/assets/images/google_logo.svg
  src/components/common/Button/Button.module.scss
  src/components/common/Checkbox/Checkbox.module.scss
  src/components/common/Checkbox/Checkbox.tsx
  src/components/common/Input/Input.tsx
  src/pages/FindId/FindId.module.scss
  src/pages/FindId/FindId.tsx
  src/pages/FindPassword/FindPassword.module.scss
  src/pages/FindPassword/FindPassword.tsx
  src/pages/LogIn/LogIn.module.scss
  src/pages/LogIn/LogIn.tsx
  src/pages/LoginSelection/LoginSelection.module.scss
  src/pages/LoginSelection/LoginSelection.tsx
  src/pages/SignUp/SignUp.module.scss
  src/pages/SignUp/SignUp.tsx
Labels: ✨feature

#25 💄 : "login selection 배경 추가"
  src/pages/LoginSelection/LoginSelection.module.scss
  src/pages/LoginSelection/LoginSelection.tsx
Labels: ♻️refactor

#32 Style/modal
  src/components/LogoutModal/LogoutModal.module.scss
  src/components/LogoutModal/LogoutModal.tsx
  src/components/PopupModal/PopupModal.module.scss
  src/components/PopupModal/PopupModal.tsx
  src/components/common/Modal/Modal.module.scss
  src/components/common/Modal/Modal.tsx
  src/pages/Home/Home.module.scss
  src/pages/Home/Home.tsx
Labels: ✨feature

#31 Style/profile modal
  src/components/header/Header.tsx
  src/components/profileModal/ProfileModal.module.scss
  src/components/profileModal/ProfileModal.tsx
Labels: ✨feature

#33 Refactor/modal
  src/components/LogoutModal/LogoutModal.module.scss
  src/components/PopupModal/PopupModal.module.scss
  src/components/PopupModal/PopupModal.tsx
Labels: ♻️refactor

#34 🐛 : "Profile modal 창 mouse leave 이벤트 수정" #30
  src/components/header/Header.tsx
  src/components/profileModal/ProfileModal.module.scss
  src/components/profileModal/ProfileModal.tsx
Labels: ♻️refactor

#35 refactor/profileModal
  src/components/profileModal/ProfileModal.module.scss
  src/components/profileModal/ProfileModal.tsx
Labels: ♻️refactor

#37 Refactor/onboarding
  src/components/AutoSlider/AutoSlider.module.scss
  src/components/Header/Header.module.scss
  src/components/Intro/Intro.module.scss
  src/components/Intro/Intro.tsx
  src/pages/OnBoarding/OnBoarding.tsx
Labels: ♻️refactor

#46 Style/search modal
  src/components/Header/Header.tsx
  src/components/SearchModal/SearchModal.module.scss
  src/components/SearchModal/SearchModal.tsx
  src/hooks/useBodyScrollLock.ts
  src/utils/currentTimes.ts
Labels: ✨feature

#62 Refactor/style/main
  src/components/MainBanner/MainBanner.module.scss
  src/components/MainBanner/MainBanner.tsx
  src/components/ScrollSlider/ScrollSlider.scss
  src/components/SwiperContent/SwiperContent.module.scss
  src/components/SwiperContent/SwiperContent.tsx
  src/components/common/SwiperContent/SwiperContent.tsx
  src/pages/Home/Home.module.scss
  src/pages/Home/Home.tsx
Labels: 🦕duplicate, ✨feature

#58 Style/loader
  package-lock.json
  package.json
  src/components/Intro/Intro.tsx
  src/components/Loader/Loader.module.scss
  src/components/Loader/Loader.tsx
  src/pages/LoginSelection/LoginSelection.tsx
  src/pages/OnBoarding/OnBoarding.tsx
Labels: ✨feature

#56 Style/detail
  src/hooks/useFilterData.ts
  src/pages/Detail/Detail.module.scss
  src/pages/Detail/Detail.tsx
  src/pages/Home/Home.tsx
  src/pages/OnBoarding/OnBoarding.tsx
Labels: ✨feature

#73 function/logOut
  src/components/LogoutModal/LogoutModal.tsx
  src/hooks/auth/index.ts
  src/hooks/auth/useAuthState.ts
  src/hooks/auth/useSignOut.ts
  src/pages/Home/Home.tsx
Labels: ✨feature

#75 Function/find password
  src/components/common/Button/Button.module.scss
  src/hooks/auth/index.ts
  src/hooks/auth/useResetPassword.ts
  src/pages/FindPassword/FindPassword.tsx
Labels: ✨feature

#76 Function/log in
  src/hooks/auth/index.ts
  src/hooks/auth/useSignIn.ts
  src/hooks/auth/useSignInWithGoogle.ts
  src/pages/LogIn/LogIn.tsx
  src/pages/LoginSelection/LoginSelection.tsx
Labels: ✨feature

#77 Feature/signup #72
  src/components/ConfirmPasswordInput/ConfirmPasswordInput.tsx
  src/components/EmailInput/EmailInput.tsx
  src/components/PasswordInput/PasswordInput.tsx
  src/components/common/Checkbox/Checkbox.tsx
  src/components/common/Input/Input.module.scss
  src/components/common/Input/Input.tsx
  src/hooks/auth/useSignUp.ts
  src/hooks/firestore/useCreateAuthUser.ts
  src/hooks/useCustomNavigate.ts
  src/pages/SignUp/SignUp.tsx
  src/state/signUpState.ts
Labels: ✨feature

#88 [refector] 회원가입
  src/components/CheckboxGroup/CheckbocGroup.tsx
  src/components/CheckboxGroup/CheckboxGroup.module.scss
  src/hooks/auth/useSignUp.ts
  src/hooks/useCustomNavigate.ts
  src/pages/SignUp/SignUp.module.scss
  src/pages/SignUp/SignUp.tsx
Labels: ♻️refactor

#83 feature/find id
  src/pages/FindId/FindId.tsx
Labels: ✨feature

#86 refactor/findPassword
  src/pages/FindPassword/FindPassword.tsx
Labels: ♻️refactor

#87 Refactor/log in
  src/components/LogoutModal/LogoutModal.tsx
  src/hooks/auth/useAuthState.ts
  src/pages/Home/Home.tsx
  src/pages/LogIn/LogIn.tsx
  src/pages/LoginSelection/LoginSelection.tsx
Labels: ♻️refactor

#93 Refector/link
  src/components/Footer/Footer.module.scss
  src/components/Footer/Footer.tsx
  src/components/Header/Header.module.scss
  src/components/Header/Header.tsx
  src/components/common/DummyLink/DummyLink.tsx
Labels: ♻️refactor

#95 Style/error page
  src/assets/images/attention_icon.svg
  src/assets/images/react.svg
  src/assets/images/vite.svg
  src/pages/ErrorPage/ErrorPage.module.scss
  src/pages/ErrorPage/ErrorPage.tsx
Labels: ✨feature
